## Main
# Background
$bg0h = 1d2021
$bg0  = 282828
$bg0s = 32302f
$bg1  = 3c3836
$bg2  = 504945
$bg3  = 665c54
$bg4  = 7c6f64
$bgray = 928374

# Foreground
$fg4 = a89984
$fg3 = bdae93
$fg2 = d5c4a1
$fg1 = ebdbb2
$fg0 = fbf1c7

# Accent
$black  = 282828
$red    = cc241d
$green  = 98971a
$yellow = d79921
$blue   = 458588
$purple = b16286
$aqua   = 689d6a
$gray   = a89984
$orange = d65d0e

# Light
$lgray   = 928374
$lred    = fb4934
$lgreen  = b8bb26
$lyellow = fabd2f
$lblue   = 83a598
$lpurple = d3869b
$laqua   = 8ec07c
$lwhite  = ebdbb2
$lorange = fe8019

## Dimmed
# Background
$bg0_dim = 1d2021
$bg1_dim = 282828
$bg2_dim = 32302f
$bg3_dim = 3c3836
$bg4_dim = 504945

# Foreground
$fg0_dim = d4be98
$fg1_dim = c5b18d
$fg2_dim = bdae93
$fg3_dim = a89984
$fg4_dim = 928374

# Accent
$red_dim    = 9d0006
$green_dim  = 79740e
$yellow_dim = b57614
$blue_dim   = 076678
$purple_dim = 8f3f71
$aqua_dim   = 427b58
$orange_dim = af3a03

# Light
$lred_dim    = d65d0e
$lgreen_dim  = 98971a
$lyellow_dim = d79921
$lblue_dim   = 458588
$lpurple_dim = b16286
$laqua_dim   = 689d6a
$lorange_dim = fe8019
